[project]
name = "mediawiki2wikijs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.31.0",
    "mwclient>=0.10.0",
    "gql>=3.4.0",
    "pypandoc>=1.11",
    "python-dotenv>=1.0.0",
    "pytest>=7.0.0",
    "responses>=0.23.0",
    "vcrpy>=4.3.0",
]
